ACCEPT = 0

#连接相关错误
HOST_ERROR = 1
USER_OR_PASSWORD_ERROR = 2
DATABASE_ERROR = 3

#插入、删除相关错误
TABELE_NOT_EXIST = 4
INSERT_VALUE_ERROR = 5
DUPLICATE_ENTRY_ERROR = 6
TYPE_ERROR = 7
DELETE_OR_UPDATE_PARENT_ROW = 8
FOREGIN_KEY_NOT_SATISFY_ERROR = 9